# Generated by Django 4.2.4 on 2023-09-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=250)),
                ('mob_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('department', models.CharField(max_length=250)),
                ('courses', models.CharField(max_length=250)),
                ('purpose', models.CharField(max_length=250)),
                ('mat_pro', models.TextField()),
            ],
        ),
    ]
